name: freeth_app
description: "Freeth client app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  go_router: ^17.2.3
  provider: ^6.1.5
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  url_launcher: ^6.3.2
  connectivity_plus: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png